const DEFAULT_CATEGORIES=["珠颈斑鸠","夜鹭","鸦科","鸲类","其他"];
const cfg=window.BIRDMEME_CONFIG||{},configured=Boolean(cfg.supabaseUrl&&!cfg.supabaseUrl.startsWith("YOUR_")&&cfg.supabaseAnonKey&&!cfg.supabaseAnonKey.startsWith("YOUR_")&&window.supabase),client=configured?window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;
let categories=["全部",...DEFAULT_CATEGORIES],subcategories=[],memes=[],active="全部",activeSub="全部",session=null,loading=true,likeCounts=new Map(),likedIds=new Set();
const $=s=>document.querySelector(s),grid=$("#grid"),loginBtn=$("#loginBtn"),logoutBtn=$("#logoutBtn"),uploadBtn=$("#uploadBtn"),adminLink=$("#adminLink"),uploadDialog=$("#uploadDialog"),uploadForm=$("#uploadForm"),editDialog=$("#editDialog"),editForm=$("#editForm"),categoryDialog=$("#categoryDialog"),categoryForm=$("#categoryForm"),loginDialog=$("#loginDialog"),cooldownKey="birdmeme-email-sent-at";
function isAdmin(){return session?.user?.id===cfg.adminUserId}
function escapeHtml(value){const node=document.createElement("div");node.textContent=String(value??"");return node.innerHTML}
function showNotice(message,kind="info"){const n=$("#notice");n.textContent=message;n.className=`notice ${kind}`;n.classList.remove("hidden");clearTimeout(showNotice.timer);showNotice.timer=setTimeout(()=>n.classList.add("hidden"),4200)}
function openImageViewer(src,alt=""){let d=$("#imageViewer");if(!d){d=document.createElement("dialog");d.id="imageViewer";d.className="image-viewer";d.innerHTML='<button class="image-viewer-close" type="button" aria-label="关闭全图">×</button><img alt="">';document.body.appendChild(d);d.querySelector("button").onclick=()=>d.close();d.onclick=e=>{if(e.target===d)d.close()}}const img=d.querySelector("img");img.src=src;img.alt=alt;d.showModal()}
async function compressForUpload(file){if(file.type==="image/gif"||file.size<900*1024)return file;try{const bitmap=await createImageBitmap(file),max=1800,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext("2d").drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const type=file.type==="image/png"?"image/webp":"image/jpeg",blob=await new Promise(resolve=>canvas.toBlob(resolve,type,.84));return blob&&blob.size<file.size?new File([blob],file.name.replace(/\.[^.]+$/,type==="image/webp"?".webp":".jpg"),{type,lastModified:Date.now()}):file}catch{return file}}
function visibleMemes(){return memes.filter(m=>(active==="全部"||m.category===active)&&(activeSub==="全部"||m.subcategory===activeSub))}
function render(){const visible=visibleMemes(),label=activeSub!=="全部"?`${active} · ${activeSub}`:`${active}分区`;$("#sectionTitle").textContent=label;$("#itemCount").textContent=loading?"加载中…":`${visible.length} 张`;$("#count").textContent=loading?"…":memes.length;$("#loading").classList.toggle("hidden",!loading);$("#empty").classList.toggle("hidden",loading||visible.length>0);grid.innerHTML=visible.map((m,i)=>`<article id="meme-${escapeHtml(m.id)}" class="card ${m.is_hidden?"hidden-card":""}" data-id="${escapeHtml(m.id)}"><div class="photo"><img src="${escapeHtml(m.image_url)}" alt="${escapeHtml(m.title)}" loading="${i<3?"eager":"lazy"}" decoding="async" ${i===0?'fetchpriority="high"':""}><span class="chip">${escapeHtml(m.subcategory||m.category)}</span></div><div class="copy"><h3>${escapeHtml(m.title)}</h3><p>${escapeHtml(m.caption)}</p>${m.author_name||m.source_name?`<p class="source-line">${m.author_name?`作者：${escapeHtml(m.author_name)}`:""}${m.author_name&&m.source_name?" · ":""}${m.source_name?m.source_url?`来源：<a href="${escapeHtml(m.source_url)}" target="_blank" rel="noopener nofollow">${escapeHtml(m.source_name)}</a>`:`来源：${escapeHtml(m.source_name)}`:""}</p>`:""}<div class="card-tools"><button class="like-button ${likedIds.has(m.id)?"liked":""}" type="button" data-action="like" aria-label="${likedIds.has(m.id)?"取消点赞":"点赞"}"><span>♥</span> ${likeCounts.get(m.id)||0}</button><button class="share-button" type="button" data-action="share">复制链接</button></div>${isAdmin()?`<div class="card-actions"><button class="edit-button" type="button" data-action="edit">编辑／隐藏</button><a class="console-shortcut" href="admin/">更多管理</a></div>`:""}</div></article>`).join("");uploadBtn.classList.toggle("hidden",!isAdmin());adminLink.classList.toggle("hidden",!isAdmin());logoutBtn.classList.toggle("hidden",!session);loginBtn.classList.toggle("hidden",Boolean(session))}
function renderSubNav(){const nav=$("#subcategories"),rows=subcategories.filter(s=>s.parent_name===active);activeSub=rows.some(s=>s.name===activeSub)?activeSub:"全部";nav.classList.toggle("hidden",active==="全部"||rows.length===0);nav.innerHTML="";if(active==="全部"||!rows.length)return;[{name:"全部"},...rows].forEach(s=>{const b=document.createElement("button");b.type="button";b.textContent=s.name;b.className=s.name===activeSub?"active":"";b.onclick=()=>{activeSub=s.name;renderSubNav();render()};nav.appendChild(b)})}
function renderNav(){const nav=$("#categories");nav.innerHTML="";categories.forEach(c=>{const b=document.createElement("button");b.textContent=c;b.className=c===active?"active":"";b.onclick=()=>{active=c;activeSub="全部";renderNav();render()};nav.appendChild(b)});if(isAdmin()){const add=document.createElement("button");add.type="button";add.className="add-category";add.textContent="＋ 增加分区";add.onclick=()=>{categoryForm.reset();$("#categoryMessage").textContent="";categoryDialog.showModal()};nav.appendChild(add)}renderSubNav()}
function subOptions(parent,selected=""){return '<option value="">不设置</option>'+subcategories.filter(s=>s.parent_name===parent).map(s=>`<option ${s.name===selected?"selected":""}>${escapeHtml(s.name)}</option>`).join("")}
function syncCategorySelects(){const options=categories.slice(1).map(c=>`<option>${escapeHtml(c)}</option>`).join("");uploadForm.category.innerHTML=`<option value="">请选择</option>${options}`;editForm.category.innerHTML=options;uploadForm.subcategory.innerHTML=subOptions(uploadForm.category.value);editForm.subcategory.innerHTML=subOptions(editForm.category.value)}
async function loadTaxonomy(){if(!client){syncCategorySelects();renderNav();return}const [c,s]=await Promise.all([client.from("categories").select("name,sort_order").order("sort_order"),client.from("subcategories").select("id,parent_name,name,sort_order").order("sort_order")]);if(!c.error&&c.data?.length)categories=["全部",...c.data.map(x=>x.name)];if(!s.error)subcategories=s.data||[];syncCategorySelects();renderNav()}
async function loadLikeCounts(){if(!client)return;const {data,error}=await client.rpc("meme_like_counts");if(!error)likeCounts=new Map((data||[]).map(x=>[x.meme_id,Number(x.like_count)]))}
async function loadOwnLikes(){likedIds=new Set();if(!client||!session)return;const {data,error}=await client.from("meme_likes").select("meme_id");if(!error)likedIds=new Set((data||[]).map(x=>x.meme_id))}
async function refreshMemes(){if(!client){loading=false;render();showNotice("网站数据服务尚未配置完成。","error");return}loading=true;render();const {data,error}=await client.from("memes").select("id,title,caption,category,subcategory,image_url,storage_path,owner_id,created_at,is_hidden,updated_at,author_name,source_name,source_url").order("created_at",{ascending:false}).limit(200);loading=false;if(error){render();showNotice(`图片加载失败：${error.message}`,"error");$("#retryLoad").classList.remove("hidden");return}$("#retryLoad").classList.add("hidden");memes=data||[];render();$("#newContent").classList.add("hidden");requestAnimationFrame(()=>{if(location.hash)document.querySelector(location.hash)?.scrollIntoView({block:"center"})})}
async function checkForNewContent(){if(!client||!memes.length||document.hidden)return;const {data}=await client.from("memes").select("id,created_at").order("created_at",{ascending:false}).limit(1).maybeSingle();if(data&&data.id!==memes[0]?.id)$("#newContent").classList.remove("hidden")}
async function initialize(){if(!client){loading=false;syncCategorySelects();renderNav();render();return}const {data}=await client.auth.getSession();session=data.session;await Promise.all([loadTaxonomy(),refreshMemes(),loadLikeCounts()]);await loadOwnLikes();render();client.auth.onAuthStateChange((_e,next)=>{session=next;setTimeout(async()=>{await loadOwnLikes();renderNav();render()},0)})}
loginBtn.onclick=()=>{if(!client)return showNotice("网站数据服务尚未配置完成。","error");$("#loginMessage").textContent="";loginDialog.showModal()};$("#closeLoginDialog").onclick=()=>loginDialog.close();
$("#emailLoginForm").onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector("button"),last=Number(localStorage.getItem(cooldownKey)||0),remaining=Math.ceil((60000-(Date.now()-last))/1000);if(remaining>0)return $("#loginMessage").textContent=`请等待 ${remaining} 秒后再发送，先检查收件箱和垃圾邮件。`;b.disabled=true;b.textContent="发送中…";const {error}=await client.auth.signInWithOtp({email:e.currentTarget.email.value.trim(),options:{shouldCreateUser:true,emailRedirectTo:location.href.split("#")[0]}});b.disabled=false;b.textContent="发送登录链接";if(error)return $("#loginMessage").textContent=error.message;localStorage.setItem(cooldownKey,String(Date.now()));$("#loginMessage").textContent="登录链接已发送，请在同一设备和浏览器中打开。"};
$("#githubLogin").onclick=async()=>{const {error}=await client.auth.signInWithOAuth({provider:"github",options:{redirectTo:new URL(".",location.href).href}});if(error)$("#loginMessage").textContent=error.message};logoutBtn.onclick=async()=>{const {error}=await client?.auth.signOut();if(error)showNotice(`退出失败：${error.message}`,"error")};
uploadBtn.onclick=()=>uploadDialog.showModal();$("#closeDialog").onclick=()=>uploadDialog.close();$("#closeEditDialog").onclick=()=>editDialog.close();$("#closeCategoryDialog").onclick=()=>categoryDialog.close();uploadForm.category.onchange=()=>uploadForm.subcategory.innerHTML=subOptions(uploadForm.category.value);editForm.category.onchange=()=>editForm.subcategory.innerHTML=subOptions(editForm.category.value);
categoryForm.onsubmit=async e=>{e.preventDefault();const message=$("#categoryMessage"),button=categoryForm.querySelector("button[type=submit]"),name=categoryForm.name.value.trim();message.textContent="";if(!client||!isAdmin())return message.textContent="当前账号没有新增分区权限";if(!name||name.length>12||name==="全部")return message.textContent="请输入 1–12 个字的有效分区名称";if(categories.includes(name))return message.textContent="这个分区已经存在";button.disabled=true;const {data,error}=await client.from("categories").insert({name,sort_order:categories.length}).select().single();button.disabled=false;if(error)return message.textContent=error.message||"添加失败";categories.push(data.name);active=data.name;syncCategorySelects();renderNav();categoryDialog.close();showNotice(`“${data.name}”分区已添加。`,"success")};
uploadForm.image.onchange=()=>{const f=uploadForm.image.files[0];if(f){$("#preview").src=URL.createObjectURL(f);$("#preview").classList.remove("hidden")}};
uploadForm.onsubmit=async e=>{e.preventDefault();const message=$("#formMessage");message.textContent="";if(!client||!isAdmin())return message.textContent="当前账号没有上传权限";const sourceFile=uploadForm.image.files[0];if(!sourceFile||sourceFile.size>8*1024*1024)return message.textContent="请选择不超过 8 MB 的图片";const button=uploadForm.querySelector("button[type=submit]");button.disabled=true;button.textContent="正在压缩…";const file=await compressForUpload(sourceFile),ext=file.name.split(".").pop().toLowerCase(),path=`${session.user.id}/${crypto.randomUUID()}.${ext}`;button.textContent="正在发布…";try{const uploaded=await client.storage.from("memes").upload(path,file,{contentType:file.type});if(uploaded.error)throw uploaded.error;const imageUrl=client.storage.from("memes").getPublicUrl(path).data.publicUrl,row={title:uploadForm.title.value.trim(),caption:uploadForm.caption.value.trim(),category:uploadForm.category.value,subcategory:uploadForm.subcategory.value||null,image_url:imageUrl,storage_path:path,owner_id:session.user.id,author_name:uploadForm.author_name.value.trim()||null,source_name:uploadForm.source_name.value.trim()||null,source_url:uploadForm.source_url.value.trim()||null};const saved=await client.from("memes").insert(row).select().single();if(saved.error){await client.storage.from("memes").remove([path]);throw saved.error}memes.unshift(saved.data);likeCounts.set(saved.data.id,0);active=saved.data.category;activeSub=saved.data.subcategory||"全部";uploadForm.reset();$("#preview").classList.add("hidden");uploadDialog.close();renderNav();render();showNotice("图片发布成功。","success")}catch(error){message.textContent=error.message||"发布失败，请稍后重试"}finally{button.disabled=false;button.textContent="发布 meme"}};
grid.onclick=async e=>{const image=e.target.closest(".photo img");if(image){openImageViewer(image.currentSrc||image.src,image.alt);return}const button=e.target.closest("button[data-action]");if(!button)return;const meme=memes.find(m=>m.id===button.closest(".card")?.dataset.id);if(!meme)return;if(button.dataset.action==="share"){const url=new URL(location.href);url.hash=`meme-${meme.id}`;try{await navigator.clipboard.writeText(url.href);showNotice("作品链接已复制。","success")}catch{prompt("复制这个作品链接：",url.href)}return}if(button.dataset.action==="like"){if(!session){$("#loginMessage").textContent="请先通过邮箱登录，再为作品点赞。";loginDialog.showModal();return}button.disabled=true;const liked=likedIds.has(meme.id),q=liked?client.from("meme_likes").delete().eq("meme_id",meme.id).eq("user_id",session.user.id):client.from("meme_likes").insert({meme_id:meme.id,user_id:session.user.id}),{error}=await q;button.disabled=false;if(error)return showNotice(error.code==="23505"?"你已经赞过这张作品":error.message,"error");liked?likedIds.delete(meme.id):likedIds.add(meme.id);likeCounts.set(meme.id,Math.max(0,(likeCounts.get(meme.id)||0)+(liked?-1:1)));render();return}if(!isAdmin())return;if(button.dataset.action==="edit"){editForm.id.value=meme.id;editForm.title.value=meme.title;editForm.caption.value=meme.caption;editForm.category.value=meme.category;editForm.subcategory.innerHTML=subOptions(meme.category,meme.subcategory||"");editForm.author_name.value=meme.author_name||"";editForm.source_name.value=meme.source_name||"";editForm.source_url.value=meme.source_url||"";editForm.is_hidden.checked=Boolean(meme.is_hidden);$("#editMessage").textContent="";editDialog.showModal()}};
editForm.onsubmit=async e=>{e.preventDefault();const message=$("#editMessage"),button=editForm.querySelector("button[type=submit]");message.textContent="";if(!client||!isAdmin())return message.textContent="当前账号没有编辑权限";button.disabled=true;const changes={title:editForm.title.value.trim(),caption:editForm.caption.value.trim(),category:editForm.category.value,subcategory:editForm.subcategory.value||null,is_hidden:editForm.is_hidden.checked,author_name:editForm.author_name.value.trim()||null,source_name:editForm.source_name.value.trim()||null,source_url:editForm.source_url.value.trim()||null},{data,error}=await client.from("memes").update(changes).eq("id",editForm.id.value).select().single();button.disabled=false;if(error)return message.textContent=error.message||"保存失败";const i=memes.findIndex(m=>m.id===data.id);if(i>=0)memes[i]=data;editDialog.close();renderSubNav();render();showNotice("修改已保存。","success")};
$("#retryLoad").onclick=refreshMemes;$("#newContent").onclick=refreshMemes;window.addEventListener("focus",checkForNewContent);document.addEventListener("visibilitychange",()=>{if(!document.hidden)checkForNewContent()});setInterval(checkForNewContent,60000);renderNav();render();initialize();
