-- 观鸟 meme：二级分区与低成本点赞（增量迁移，可重复执行）
-- 不删除或重写任何现有 meme、专题或投票记录。

begin;

create table if not exists public.subcategories(
  id bigint generated by default as identity primary key,
  parent_name text not null references public.categories(name) on update cascade on delete cascade,
  name text not null check(name=btrim(name) and char_length(name) between 1 and 16),
  sort_order integer not null default 100,
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  unique(parent_name,name)
);
insert into public.subcategories(parent_name,name,sort_order,created_by)
values
  ('鸲类','北红尾鸲',1,'e06f43d2-f022-43ec-87bc-9d0b36ce5b4f'),
  ('鸲类','红尾水鸲',2,'e06f43d2-f022-43ec-87bc-9d0b36ce5b4f')
on conflict(parent_name,name) do nothing;

alter table public.subcategories enable row level security;
revoke insert,update,delete on public.subcategories from anon;
grant select on public.subcategories to anon,authenticated;
grant insert,update,delete on public.subcategories to authenticated;
grant usage,select on sequence public.subcategories_id_seq to authenticated;
drop policy if exists "Public can read subcategories" on public.subcategories;
create policy "Public can read subcategories" on public.subcategories for select using(true);
drop policy if exists "Admin can insert subcategories" on public.subcategories;
create policy "Admin can insert subcategories" on public.subcategories for insert to authenticated with check(
  (select auth.uid())='e06f43d2-f022-43ec-87bc-9d0b36ce5b4f'::uuid and created_by=(select auth.uid())
);
drop policy if exists "Admin can update subcategories" on public.subcategories;
create policy "Admin can update subcategories" on public.subcategories for update to authenticated
using((select auth.uid())='e06f43d2-f022-43ec-87bc-9d0b36ce5b4f'::uuid)
with check((select auth.uid())='e06f43d2-f022-43ec-87bc-9d0b36ce5b4f'::uuid);
drop policy if exists "Admin can delete subcategories" on public.subcategories;
create policy "Admin can delete subcategories" on public.subcategories for delete to authenticated
using((select auth.uid())='e06f43d2-f022-43ec-87bc-9d0b36ce5b4f'::uuid);

alter table public.memes add column if not exists subcategory text;
-- 使用触发器验证一级/二级关系，同时允许现有记录的二级分区为空。
create or replace function public.validate_meme_subcategory()
returns trigger language plpgsql set search_path=public,pg_temp as $$
begin
  if new.subcategory is not null and not exists(
    select 1 from public.subcategories s where s.parent_name=new.category and s.name=new.subcategory
  ) then raise exception '二级分区不属于所选一级分区'; end if;
  return new;
end $$;
drop trigger if exists validate_meme_subcategory on public.memes;
create trigger validate_meme_subcategory before insert or update of category,subcategory on public.memes
for each row execute function public.validate_meme_subcategory();

create table if not exists public.meme_likes(
  meme_id uuid not null references public.memes(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(meme_id,user_id)
);
create index if not exists meme_likes_meme_id_idx on public.meme_likes(meme_id);
alter table public.meme_likes enable row level security;
revoke all on public.meme_likes from anon;
revoke update on public.meme_likes from authenticated;
grant select,insert,delete on public.meme_likes to authenticated;
drop policy if exists "Users can read own likes" on public.meme_likes;
create policy "Users can read own likes" on public.meme_likes for select to authenticated
using(user_id=(select auth.uid()) or (select auth.uid())='e06f43d2-f022-43ec-87bc-9d0b36ce5b4f'::uuid);
drop policy if exists "Users can like once" on public.meme_likes;
create policy "Users can like once" on public.meme_likes for insert to authenticated with check(
  user_id=(select auth.uid()) and exists(
    select 1 from public.memes m where m.id=public.meme_likes.meme_id and m.is_hidden=false
  )
);
drop policy if exists "Users can remove own likes" on public.meme_likes;
create policy "Users can remove own likes" on public.meme_likes for delete to authenticated
using(user_id=(select auth.uid()));

create or replace function public.meme_like_counts()
returns table(meme_id uuid,like_count bigint)
language sql security definer set search_path=public,pg_temp stable
as $$
  select l.meme_id,count(*)::bigint from public.meme_likes l
  join public.memes m on m.id=l.meme_id and m.is_hidden=false
  group by l.meme_id
$$;
revoke all on function public.meme_like_counts() from public;
grant execute on function public.meme_like_counts() to anon,authenticated;

commit;
