-- 夜鹭模仿大赛：参赛编号、邮箱用户每日一票、公开聚合榜单。
-- 北京时间自然日计算；不修改 memes 表和 Storage 图片。
create table if not exists public.night_heron_contest_entries (
  meme_id uuid primary key references public.memes(id) on delete cascade,
  contest_number integer,
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now()
);
alter table public.night_heron_contest_entries add column if not exists contest_number integer;
with numbered as (
  select meme_id,row_number() over(order by created_at,meme_id)::integer n
  from public.night_heron_contest_entries where contest_number is null
) update public.night_heron_contest_entries e set contest_number=n.n from numbered n where e.meme_id=n.meme_id;
alter table public.night_heron_contest_entries alter column contest_number set not null;
create unique index if not exists night_heron_contest_number_key on public.night_heron_contest_entries(contest_number);
alter table public.night_heron_contest_entries enable row level security;
grant select on public.night_heron_contest_entries to anon,authenticated;
grant insert,delete on public.night_heron_contest_entries to authenticated;
drop policy if exists "Public can read night heron contest" on public.night_heron_contest_entries;
create policy "Public can read night heron contest" on public.night_heron_contest_entries for select using(true);
drop policy if exists "Admin can add night heron contest entries" on public.night_heron_contest_entries;
create policy "Admin can add night heron contest entries" on public.night_heron_contest_entries for insert to authenticated with check(
 (select auth.uid())='e06f43d2-f022-43ec-87bc-9d0b36ce5b4f'::uuid and created_by=(select auth.uid())
);
drop policy if exists "Admin can remove night heron contest entries" on public.night_heron_contest_entries;
create policy "Admin can remove night heron contest entries" on public.night_heron_contest_entries for delete to authenticated using(
 (select auth.uid())='e06f43d2-f022-43ec-87bc-9d0b36ce5b4f'::uuid
);

create table if not exists public.night_heron_votes(
 id bigint generated by default as identity primary key,
 meme_id uuid not null references public.night_heron_contest_entries(meme_id) on delete cascade,
 user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
 vote_day date not null default (timezone('Asia/Shanghai',now()))::date,
 created_at timestamptz not null default now(),
 unique(user_id,vote_day)
);
alter table public.night_heron_votes enable row level security;
grant select,insert on public.night_heron_votes to authenticated;
drop policy if exists "Users can read own night heron votes" on public.night_heron_votes;
create policy "Users can read own night heron votes" on public.night_heron_votes for select to authenticated using(user_id=(select auth.uid()));
drop policy if exists "Users get one vote per Beijing day" on public.night_heron_votes;
create policy "Users get one vote per Beijing day" on public.night_heron_votes for insert to authenticated with check(
 user_id=(select auth.uid()) and vote_day=(timezone('Asia/Shanghai',now()))::date
);

create or replace function public.night_heron_leaderboard()
returns table(meme_id uuid,contest_number integer,title text,vote_count bigint)
language sql security definer set search_path=public,pg_temp stable
as $$ select e.meme_id,e.contest_number,m.title,count(v.id)::bigint
from public.night_heron_contest_entries e join public.memes m on m.id=e.meme_id
left join public.night_heron_votes v on v.meme_id=e.meme_id
group by e.meme_id,e.contest_number,m.title order by count(v.id) desc,e.contest_number asc $$;
revoke all on function public.night_heron_leaderboard() from public;
grant execute on function public.night_heron_leaderboard() to anon,authenticated;
