const cfg=window.BIRDMEME_CONFIG||{},client=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey),$=s=>document.querySelector(s);
let session=null,memes=[],categories=[],subcategories=[],entries=[],ranking=[],likeCounts=new Map(),settings={id:1,is_open:true,ends_at:null};
const esc=v=>{const d=document.createElement("div");d.textContent=String(v??"");return d.innerHTML},admin=()=>session?.user?.id===cfg.adminUserId,fmt=v=>v?new Intl.DateTimeFormat("zh-CN",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Shanghai"}).format(new Date(v)):"—";
function notice(t,k="success"){const n=$("#notice");n.textContent=t;n.className=`notice ${k}`;clearTimeout(notice.timer);notice.timer=setTimeout(()=>n.classList.add("hidden"),4200)}
function options(selected=""){return categories.map(c=>`<option ${c.name===selected?"selected":""}>${esc(c.name)}</option>`).join("")}
function subOptions(parent,selected=""){return '<option value="">不设置</option>'+subcategories.filter(s=>s.parent_name===parent).map(s=>`<option ${s.name===selected?"selected":""}>${esc(s.name)}</option>`).join("")}
function renderStats(){const hidden=memes.filter(m=>m.is_hidden).length,last=memes[0]?.created_at;$("#stats").innerHTML=`<div class="stat"><b>${memes.length}</b><span>全部作品</span></div><div class="stat"><b>${hidden}</b><span>已隐藏</span></div><div class="stat"><b>${entries.length}</b><span>专题入选</span></div><div class="stat"><b>${last?fmt(last):"—"}</b><span>最近上传</span></div>`}
function filtered(){const q=$("#search").value.trim().toLowerCase(),c=$("#categoryFilter").value,v=$("#visibilityFilter").value;return memes.filter(m=>(!q||[m.title,m.caption,m.author_name,m.source_name].some(x=>String(x||"").toLowerCase().includes(q)))&&(!c||m.category===c)&&(!v||(v==="hidden")===Boolean(m.is_hidden)))}
function renderWorks(){$("#workList").innerHTML=filtered().map(m=>`<article class="work-row" data-id="${m.id}"><img src="${esc(m.image_url)}" alt="" loading="lazy" decoding="async"><div><h3>${esc(m.title)}</h3><div class="meta"><span class="pill">${esc(m.category)}${m.subcategory?` · ${esc(m.subcategory)}`:""}</span><span class="pill">♥ ${likeCounts.get(m.id)||0}</span>${m.is_hidden?'<span class="pill hidden-state">已隐藏</span>':""}<span>上传 ${fmt(m.created_at)}</span><span>修改 ${fmt(m.updated_at)}</span></div></div><div class="row-actions"><button class="soft" data-action="edit">编辑</button><button class="warning" data-action="toggle">${m.is_hidden?"恢复公开":"隐藏"}</button><button class="danger" data-action="delete">永久删除</button></div></article>`).join("")||'<div class="empty">没有符合条件的作品</div>'}
function renderContest(){const eMap=new Map(entries.map(e=>[e.meme_id,e])),rMap=new Map(ranking.map(r=>[r.meme_id,r.vote_count]));$("#contestList").innerHTML=memes.filter(m=>m.category==="夜鹭"&&!m.is_hidden).map(m=>{const e=eMap.get(m.id);return `<article class="contest-row" data-id="${m.id}"><img src="${esc(m.image_url)}" alt="" loading="lazy"><div><h3>${esc(m.title)}</h3><div class="meta"><span>${e?`当前编号 #${e.contest_number}`:"未入选"}</span><span>${e?`${rMap.get(m.id)||0} 票`:""}</span></div></div><div class="row-actions">${e?`<input class="contest-number-input" type="number" min="1" value="${e.contest_number}" aria-label="作品编号"><button class="soft" data-action="number">修改编号</button><button class="warning" data-action="remove">移出专题</button>`:'<button class="soft" data-action="add">加入专题</button>'}</div></article>`}).join("")||'<div class="empty">夜鹭分区暂无公开作品</div>';const f=$("#contestForm");f.is_open.checked=settings.is_open;f.ends_at.value=settings.ends_at?new Date(new Date(settings.ends_at).getTime()-new Date(settings.ends_at).getTimezoneOffset()*60000).toISOString().slice(0,16):""}
function renderCategories(){$("#categoryList").innerHTML=categories.map(c=>`<span>${esc(c.name)} · ${c.sort_order}</span>`).join("");$("#subcategoryList").innerHTML=categories.map(c=>{const rows=subcategories.filter(s=>s.parent_name===c.name);return rows.length?`<section><strong>${esc(c.name)}</strong>${rows.map(s=>`<span>${esc(s.name)}</span>`).join("")}</section>`:""}).join("");$("#categoryFilter").innerHTML='<option value="">全部分区</option>'+options();$("#editForm").category.innerHTML=options();$("#subcategoryForm").parent_name.innerHTML=options()}
function render(){renderStats();renderCategories();renderWorks();renderContest()}
async function load(){const [m,c,sc,e,s,r,l]=await Promise.all([client.from("memes").select("id,title,caption,category,subcategory,image_url,storage_path,owner_id,created_at,updated_at,is_hidden,hidden_at,author_name,source_name,source_url").order("created_at",{ascending:false}).limit(500),client.from("categories").select("name,sort_order,created_at").order("sort_order"),client.from("subcategories").select("id,parent_name,name,sort_order,created_at").order("sort_order"),client.from("night_heron_contest_entries").select("meme_id,contest_number,created_at").order("contest_number"),client.from("night_heron_contest_settings").select("id,is_open,ends_at,updated_at").eq("id",1).maybeSingle(),client.rpc("night_heron_leaderboard"),client.rpc("meme_like_counts")]);if(m.error)return notice(`作品加载失败：${m.error.message}`,"error");memes=m.data||[];categories=c.data||[];subcategories=sc.data||[];entries=e.data||[];if(s.data)settings=s.data;ranking=r.data||[];likeCounts=new Map((l.data||[]).map(x=>[x.meme_id,Number(x.like_count)]));render()}
async function init(){const {data}=await client.auth.getSession();session=data.session;if(!admin()){if(session)await client.auth.signOut();$("#gate").classList.remove("hidden");return}$("#gate").classList.add("hidden");$("#console").classList.remove("hidden");$("#logoutBtn").classList.remove("hidden");await load()}
$("#loginBtn").onclick=async()=>{const {error}=await client.auth.signInWithOAuth({provider:"github",options:{redirectTo:location.href}});if(error)$("#gateMessage").textContent=error.message};$("#logoutBtn").onclick=async()=>{await client.auth.signOut();location.reload()};
document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tabs button").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".panel").forEach(x=>x.classList.toggle("hidden",x.id!==b.dataset.tab))});["#search","#categoryFilter","#visibilityFilter"].forEach(s=>$(s).addEventListener("input",renderWorks));
$("#workList").onclick=async ev=>{const b=ev.target.closest("button"),row=ev.target.closest(".work-row");if(!b||!row)return;const m=memes.find(x=>x.id===row.dataset.id);if(b.dataset.action==="edit"){const f=$("#editForm");["id","title","caption","category","author_name","source_name","source_url"].forEach(k=>f[k].value=m[k]||"");f.subcategory.innerHTML=subOptions(m.category,m.subcategory||"");f.is_hidden.checked=m.is_hidden;$("#editMessage").textContent="";$("#editDialog").showModal()}if(b.dataset.action==="toggle"){if(!confirm(m.is_hidden?`恢复公开“${m.title}”？`:`立即隐藏“${m.title}”？普通访客将看不到它。`))return;const {error}=await client.from("memes").update({is_hidden:!m.is_hidden}).eq("id",m.id);if(error)return notice(error.message,"error");await load();notice(m.is_hidden?"作品已恢复公开":"作品已隐藏")}if(b.dataset.action==="delete"){$("#deleteForm").id.value=m.id;$("#deleteForm").confirm_title.value="";$("#deleteTitle").textContent=`“${m.title}”`;$("#deleteDialog").showModal()}};
$("#editForm").category.onchange=e=>$("#editForm").subcategory.innerHTML=subOptions(e.target.value);
$("#editForm").onsubmit=async ev=>{ev.preventDefault();const f=ev.currentTarget,id=f.id.value,row={title:f.title.value.trim(),caption:f.caption.value.trim(),category:f.category.value,subcategory:f.subcategory.value||null,author_name:f.author_name.value.trim()||null,source_name:f.source_name.value.trim()||null,source_url:f.source_url.value.trim()||null,is_hidden:f.is_hidden.checked};const {error}=await client.from("memes").update(row).eq("id",id);if(error)return $("#editMessage").textContent=error.message;$("#editDialog").close();await load();notice("作品修改已保存")};
$("#deleteForm").onsubmit=async ev=>{ev.preventDefault();const f=ev.currentTarget,m=memes.find(x=>x.id===f.id.value);if(f.confirm_title.value!==m.title)return notice("输入的标题不一致，未执行删除","error");const {error}=await client.from("memes").delete().eq("id",m.id);if(error)return notice(error.message,"error");if(m.storage_path)await client.storage.from("memes").remove([m.storage_path]);$("#deleteDialog").close();await load();notice("作品已永久删除")};
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>b.closest("dialog").close());
$("#contestList").onclick=async ev=>{const b=ev.target.closest("button"),row=ev.target.closest(".contest-row");if(!b||!row)return;const id=row.dataset.id,e=entries.find(x=>x.meme_id===id);let q;if(b.dataset.action==="add")q=client.from("night_heron_contest_entries").insert({meme_id:id,contest_number:entries.reduce((n,x)=>Math.max(n,x.contest_number),0)+1,created_by:session.user.id});if(b.dataset.action==="remove"){if(!confirm("移出专题不会删除主页作品和历史票数。确定移出？"))return;q=client.from("night_heron_contest_entries").delete().eq("meme_id",id)}if(b.dataset.action==="number"){const n=Number(row.querySelector("input").value);if(!Number.isInteger(n)||n<1)return notice("请输入正整数编号","error");q=client.from("night_heron_contest_entries").update({contest_number:n}).eq("meme_id",id)}if(!q)return;const {error}=await q;if(error)return notice(error.code==="23505"?"这个编号已经被使用":error.message,"error");await load();notice("专题设置已更新")};
$("#contestForm").onsubmit=async ev=>{ev.preventDefault();const f=ev.currentTarget,row={id:1,is_open:f.is_open.checked,ends_at:f.ends_at.value?new Date(f.ends_at.value).toISOString():null,updated_by:session.user.id};if(!confirm(row.is_open?"确定保存投票设置？":"确定关闭投票？关闭后用户将无法投票。"))return;const {error}=await client.from("night_heron_contest_settings").upsert(row);if(error)return notice(error.message,"error");settings=row;renderContest();notice("投票设置已保存")};
$("#categoryForm").onsubmit=async ev=>{ev.preventDefault();const f=ev.currentTarget,name=f.name.value.trim();if(categories.some(c=>c.name===name))return notice("分区已经存在","error");const {error}=await client.from("categories").insert({name,sort_order:categories.reduce((n,c)=>Math.max(n,c.sort_order),0)+1,created_by:session.user.id});if(error)return notice(error.message,"error");f.reset();await load();notice(`“${name}”分区已增加`)};
$("#subcategoryForm").onsubmit=async ev=>{ev.preventDefault();const f=ev.currentTarget,parent_name=f.parent_name.value,name=f.name.value.trim();if(subcategories.some(s=>s.parent_name===parent_name&&s.name===name))return notice("这个二级分区已经存在","error");const siblings=subcategories.filter(s=>s.parent_name===parent_name),{error}=await client.from("subcategories").insert({parent_name,name,sort_order:siblings.reduce((n,s)=>Math.max(n,s.sort_order),0)+1,created_by:session.user.id});if(error)return notice(error.message,"error");f.name.value="";await load();notice(`“${parent_name} → ${name}”已增加`)};
$("#exportBtn").onclick=async()=>{const [{data:votes,error},{data:likes,error:likeError}]=await Promise.all([client.from("night_heron_votes").select("id,meme_id,user_id,vote_day,created_at").order("created_at"),client.from("meme_likes").select("meme_id,user_id,created_at").order("created_at")]);if(error||likeError)return notice("数据读取失败，请检查最新安全 SQL 是否已执行","error");const payload={exported_at:new Date().toISOString(),memes,categories,subcategories,night_heron_contest_entries:entries,night_heron_contest_settings:settings,night_heron_votes:votes,meme_likes:likes};const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));a.download=`birdwatchmeme-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);notice("数据备份已下载")};
client.auth.onAuthStateChange(()=>setTimeout(init,0));init();
