plugins {
    id 'com.android.application'
}

android {
    namespace 'com.weirdcore.twoworlds'
    compileSdk 35

    defaultConfig {
        applicationId 'com.weirdcore.twoworlds'
        minSdk 23
        targetSdk 35
        versionCode 20
        versionName '2.0'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
